#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 -U postgres <<-EOSQL
  CREATE USER "$PG_USER" WITH PASSWORD '$"PG_USER"';
  CREATE DATABASE "$PG_DB";
  GRANT ALL PRIVILEGES ON DATABASE "$PG_DB" TO "$PG_USER";
EOSQL
