version: '3'

services:
  postgres:
    image: postgres:13.4-alpine
    volumes:
      - ./infra/postgres/db-init:/docker-entrypoint-initdb.d
    ports:
      - "6543:5432"
    env_file:
      - .docker.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - docker_network

  bmb:
    tty: true
    build: infra/service
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - .docker.env
    networks:
      - docker_network
    command: python ./manage.py runserver 0.0.0.0:8000

networks:
  docker_network:
    driver: bridge
