# Generated by Django 4.2.4 on 2023-08-21 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменена')),
                ('page_title', models.CharField(verbose_name='Заголовок страницы')),
                ('short_description', models.TextField(default='', verbose_name='Краткое описание')),
                ('page_url', models.URLField(unique=True, verbose_name='Ссылка на страницу')),
                ('preview', models.ImageField(upload_to='', verbose_name='Картинка превью')),
            ],
            options={
                'verbose_name': 'Закладка',
                'verbose_name_plural': 'Закладки',
            },
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('cypher', models.CharField(primary_key=True, serialize=False, verbose_name='Шифр')),
                ('description', models.CharField(default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип ссылки',
                'verbose_name_plural': 'Типы ссылок',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменена')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
                ('short_description', models.TextField(default='', verbose_name='Краткое описание')),
                ('bookmarks', models.ManyToManyField(to='bookmarks_collection.bookmark')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.AddField(
            model_name='bookmark',
            name='page_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookmarks_collection.linktype', verbose_name='Тип ссылки'),
        ),
    ]
