# Generated by Django 4.2.4 on 2023-08-26 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks_collection', '0002_bookmark_user_collection_user_alter_bookmark_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='page_url',
            field=models.URLField(verbose_name='Ссылка на страницу'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('page_url', 'user')},
        ),
    ]
